= [Bi]nary [SCons]
:author: MizunagiKB
:copyright: 2023 MizunagiKB <mizukb@live.jp>
:doctype: book
:toc:
:toclevels: 3
:lang: ja
:encoding: utf-8
:stylesdir: ./doc/res/theme/css
:stylesheet: adoc-golo.css
:source-highlighter: highlight.js
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

link:README.adoc[English] / link:README.ja.adoc[Japanese]


== About biscons

このプログラムはSConsを利用する場面で、手間となるセットアップを不要とするためのものです。

SConsを実行するために必要なものをまとめてあるので、必要な時にダウンロードしてすぐに利用可能です。


=== 使い方

ビルド対象のSConst対応プロジェクト直下に _bi.scons_ というフォルダを作成して配置してください。

使用方法と機能は _Python3.10_ で動かすSConsと同じです。


.Example
[source, zsh]
----
bi.scons/biscons --help
----


=== ビルド方法

Windows(x86_64)::

[source, zsh]
----
env.windows-x86_64.bat
python setup.py build
----

macOS(Arm64)::

[source, zsh]
----
env.macos-arm64.bat
python setup.py build
----


=== ライセンス

このソフトウェアは MIT License として提供されます。

このソフトウェアが依存する各種ソフトウェアについては licenses フォルダを参照してください。

cx_Freeze::
cx_Freeze uses a license derived from the link:https://www.python.org/psf/license[Python Software Foundation License].
You can read the cx_Freeze license in the link:https://cx-freeze.readthedocs.io/en/latest/license.html[documentation] or in the link:https://github.com/marcelotduarte/cx_Freeze/blob/main/doc/src/license.rst[source repository].


== 関連情報
* link:https://github.com/indygreg/python-build-standalone[Python build standalone (GitHub)]
* link:https://github.com/SCons/scons[SCons (GitHub)]
* link:https://github.com/marcelotduarte/cx_Freeze[cx_Freeze (GitHub)]
