= [Bi]nary [SCons]
:author: MizunagiKB
:copyright: 2023 MizunagiKB <mizukb@live.jp>
:doctype: book
:toc:
:toclevels: 3
:lang: ja
:encoding: utf-8
:stylesdir: ./doc/res/theme/css
:stylesheet: adoc-golo.css
:source-highlighter: highlight.js
:experimental:
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
endif::[]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

link:README.adoc[Japanese] / link:README.en.adoc[English]


image::https://github.com/MizunagiKB/biscons/actions/workflows/dist-linux-x86_64.yaml/badge.svg[]
image::https://github.com/MizunagiKB/biscons/actions/workflows/dist-macos-x86_64.yaml/badge.svg[]
image::https://github.com/MizunagiKB/biscons/actions/workflows/dist-win-x86_64.yaml/badge.svg[]


== About biscons

This program is designed to eliminate the hassle of setup when using SCons.

It has everything you need to run SCons, so you can download it and use it when you need it.


== Usage

Create and place a folder called _bi.scons_ directly under the SConst-enabled project to be built.

Usage and functionality are the same as SCons running in _Python3.10_.


.Example
[source, zsh]
----
bi.scons/biscons --help
----


== Build

Windows(x86_64)::

[source, zsh]
----
env.windows-x86_64.bat
python setup.py build
----

macOS(Arm64)::

[source, zsh]
----
env.macos-arm64.bat
python setup.py build
----


=== License

This software is provided as an MIT License.

See the licenses folder for information about the various software on which this software depends.


cx_Freeze::
cx_Freeze uses a license derived from the link:https://www.python.org/psf/license[Python Software Foundation License].
You can read the cx_Freeze license in the link:https://cx-freeze.readthedocs.io/en/latest/license.html[documentation] or in the link:https://github.com/marcelotduarte/cx_Freeze/blob/main/doc/src/license.rst[source repository].


== Related Information
* link:https://github.com/indygreg/python-build-standalone[Python build standalone (GitHub)]
* link:https://github.com/SCons/scons[SCons (GitHub)]
* link:https://github.com/marcelotduarte/cx_Freeze[cx_Freeze (GitHub)]
